version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - modernize
    - nilerr
    - noctx
    - revive
    - sqlclosecheck
    - unconvert
    - usestdlibvars
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/feytox/kabanbot
