// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const chatsBySummaryModel = `-- name: ChatsBySummaryModel :many
SELECT id, title, enabled, summary_model_id, chat_model_id, personality, settings_json, updated_by, updated_at, member FROM chats WHERE summary_model_id = ? ORDER BY title
`

func (q *Queries) ChatsBySummaryModel(ctx context.Context, summaryModelID sql.NullInt64) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, chatsBySummaryModel, summaryModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Enabled,
			&i.SummaryModelID,
			&i.ChatModelID,
			&i.Personality,
			&i.SettingsJson,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Member,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChat = `-- name: GetChat :one
SELECT id, title, enabled, summary_model_id, chat_model_id, personality, settings_json, updated_by, updated_at, member FROM chats WHERE id = ?
`

func (q *Queries) GetChat(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Enabled,
		&i.SummaryModelID,
		&i.ChatModelID,
		&i.Personality,
		&i.SettingsJson,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Member,
	)
	return i, err
}

const memberChats = `-- name: MemberChats :many
SELECT id, title, enabled, summary_model_id, chat_model_id, personality, settings_json, updated_by, updated_at, member FROM chats WHERE member ORDER BY title
`

func (q *Queries) MemberChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, memberChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Enabled,
			&i.SummaryModelID,
			&i.ChatModelID,
			&i.Personality,
			&i.SettingsJson,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Member,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchChat = `-- name: TouchChat :exec
INSERT INTO chats (id, title, member) VALUES (?, ?, ?)
ON CONFLICT (id) DO UPDATE SET title = excluded.title, member = excluded.member
`

type TouchChatParams struct {
	ID     int64
	Title  string
	Member bool
}

// Records that the bot is (or is no longer) in the chat.
func (q *Queries) TouchChat(ctx context.Context, arg TouchChatParams) error {
	_, err := q.db.ExecContext(ctx, touchChat, arg.ID, arg.Title, arg.Member)
	return err
}

const unbindSummaryModel = `-- name: UnbindSummaryModel :exec
UPDATE chats SET summary_model_id = NULL, updated_at = unixepoch()
WHERE id = ? AND summary_model_id = ?
`

type UnbindSummaryModelParams struct {
	ID             int64
	SummaryModelID sql.NullInt64
}

func (q *Queries) UnbindSummaryModel(ctx context.Context, arg UnbindSummaryModelParams) error {
	_, err := q.db.ExecContext(ctx, unbindSummaryModel, arg.ID, arg.SummaryModelID)
	return err
}

const updateChatSettings = `-- name: UpdateChatSettings :exec
UPDATE chats
SET enabled = ?, settings_json = ?, summary_model_id = ?, updated_by = ?, updated_at = unixepoch()
WHERE id = ?
`

type UpdateChatSettingsParams struct {
	Enabled        bool
	SettingsJson   string
	SummaryModelID sql.NullInt64
	UpdatedBy      sql.NullInt64
	ID             int64
}

func (q *Queries) UpdateChatSettings(ctx context.Context, arg UpdateChatSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateChatSettings,
		arg.Enabled,
		arg.SettingsJson,
		arg.SummaryModelID,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
