// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const chatsByModel = `-- name: ChatsByModel :many
SELECT id, title, enabled, summary_model_id, chat_model_id, personality, settings_json, updated_by, updated_at, member, summary_style FROM chats WHERE summary_model_id = ?1 OR chat_model_id = ?1 ORDER BY title
`

// Chats that use the model for summaries or for chatting.
func (q *Queries) ChatsByModel(ctx context.Context, modelID sql.NullInt64) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, chatsByModel, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Enabled,
			&i.SummaryModelID,
			&i.ChatModelID,
			&i.Personality,
			&i.SettingsJson,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Member,
			&i.SummaryStyle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChat = `-- name: GetChat :one
SELECT id, title, enabled, summary_model_id, chat_model_id, personality, settings_json, updated_by, updated_at, member, summary_style FROM chats WHERE id = ?
`

func (q *Queries) GetChat(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Enabled,
		&i.SummaryModelID,
		&i.ChatModelID,
		&i.Personality,
		&i.SettingsJson,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Member,
		&i.SummaryStyle,
	)
	return i, err
}

const getPersonalityChange = `-- name: GetPersonalityChange :one
SELECT id, chat_id, text, changed_by, via, created_at FROM personality_history WHERE id = ?
`

func (q *Queries) GetPersonalityChange(ctx context.Context, id int64) (PersonalityHistory, error) {
	row := q.db.QueryRowContext(ctx, getPersonalityChange, id)
	var i PersonalityHistory
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Text,
		&i.ChangedBy,
		&i.Via,
		&i.CreatedAt,
	)
	return i, err
}

const insertPersonalityChange = `-- name: InsertPersonalityChange :exec
INSERT INTO personality_history (chat_id, text, changed_by, via) VALUES (?, ?, ?, ?)
`

type InsertPersonalityChangeParams struct {
	ChatID    int64
	Text      string
	ChangedBy int64
	Via       string
}

func (q *Queries) InsertPersonalityChange(ctx context.Context, arg InsertPersonalityChangeParams) error {
	_, err := q.db.ExecContext(ctx, insertPersonalityChange,
		arg.ChatID,
		arg.Text,
		arg.ChangedBy,
		arg.Via,
	)
	return err
}

const memberChats = `-- name: MemberChats :many
SELECT id, title, enabled, summary_model_id, chat_model_id, personality, settings_json, updated_by, updated_at, member, summary_style FROM chats WHERE member ORDER BY title
`

func (q *Queries) MemberChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, memberChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Enabled,
			&i.SummaryModelID,
			&i.ChatModelID,
			&i.Personality,
			&i.SettingsJson,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Member,
			&i.SummaryStyle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const personalityHistory = `-- name: PersonalityHistory :many
SELECT personality_history.id, personality_history.chat_id, personality_history.text, personality_history.changed_by, personality_history.via, personality_history.created_at, coalesce(users.username, '') AS username, coalesce(users.first_name, '') AS first_name
FROM personality_history
LEFT JOIN users ON users.id = personality_history.changed_by
WHERE chat_id = ?
ORDER BY personality_history.id DESC
LIMIT ?
`

type PersonalityHistoryParams struct {
	ChatID int64
	Limit  int64
}

type PersonalityHistoryRow struct {
	ID        int64
	ChatID    int64
	Text      string
	ChangedBy int64
	Via       string
	CreatedAt int64
	Username  string
	FirstName string
}

func (q *Queries) PersonalityHistory(ctx context.Context, arg PersonalityHistoryParams) ([]PersonalityHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, personalityHistory, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalityHistoryRow
	for rows.Next() {
		var i PersonalityHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Text,
			&i.ChangedBy,
			&i.Via,
			&i.CreatedAt,
			&i.Username,
			&i.FirstName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPersonality = `-- name: SetPersonality :exec
UPDATE chats SET personality = ?, updated_by = ?, updated_at = unixepoch() WHERE id = ?
`

type SetPersonalityParams struct {
	Personality string
	UpdatedBy   sql.NullInt64
	ID          int64
}

func (q *Queries) SetPersonality(ctx context.Context, arg SetPersonalityParams) error {
	_, err := q.db.ExecContext(ctx, setPersonality, arg.Personality, arg.UpdatedBy, arg.ID)
	return err
}

const setSummaryStyle = `-- name: SetSummaryStyle :exec
UPDATE chats SET summary_style = ?, updated_by = ?, updated_at = unixepoch() WHERE id = ?
`

type SetSummaryStyleParams struct {
	SummaryStyle string
	UpdatedBy    sql.NullInt64
	ID           int64
}

func (q *Queries) SetSummaryStyle(ctx context.Context, arg SetSummaryStyleParams) error {
	_, err := q.db.ExecContext(ctx, setSummaryStyle, arg.SummaryStyle, arg.UpdatedBy, arg.ID)
	return err
}

const touchChat = `-- name: TouchChat :exec
INSERT INTO chats (id, title, member) VALUES (?, ?, ?)
ON CONFLICT (id) DO UPDATE SET title = excluded.title, member = excluded.member
`

type TouchChatParams struct {
	ID     int64
	Title  string
	Member bool
}

// Records that the bot is (or is no longer) in the chat.
func (q *Queries) TouchChat(ctx context.Context, arg TouchChatParams) error {
	_, err := q.db.ExecContext(ctx, touchChat, arg.ID, arg.Title, arg.Member)
	return err
}

const unbindModel = `-- name: UnbindModel :exec
UPDATE chats
SET summary_model_id = CASE WHEN summary_model_id = ?1 THEN NULL ELSE summary_model_id END,
    chat_model_id = CASE WHEN chat_model_id = ?1 THEN NULL ELSE chat_model_id END,
    updated_at = unixepoch()
WHERE id = ?2
`

type UnbindModelParams struct {
	ModelID sql.NullInt64
	ChatID  int64
}

func (q *Queries) UnbindModel(ctx context.Context, arg UnbindModelParams) error {
	_, err := q.db.ExecContext(ctx, unbindModel, arg.ModelID, arg.ChatID)
	return err
}

const updateChatSettings = `-- name: UpdateChatSettings :exec
UPDATE chats
SET enabled = ?, settings_json = ?, summary_model_id = ?, chat_model_id = ?, updated_by = ?, updated_at = unixepoch()
WHERE id = ?
`

type UpdateChatSettingsParams struct {
	Enabled        bool
	SettingsJson   string
	SummaryModelID sql.NullInt64
	ChatModelID    sql.NullInt64
	UpdatedBy      sql.NullInt64
	ID             int64
}

func (q *Queries) UpdateChatSettings(ctx context.Context, arg UpdateChatSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateChatSettings,
		arg.Enabled,
		arg.SettingsJson,
		arg.SummaryModelID,
		arg.ChatModelID,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
