// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const chatUsers = `-- name: ChatUsers :many
SELECT user_id, username, max(message_id) AS last_message_id
FROM messages
WHERE chat_id = ? AND user_id != 0 AND NOT is_bot
GROUP BY user_id
`

type ChatUsersRow struct {
	UserID        int64
	Username      string
	LastMessageID interface{}
}

// Every human who wrote in the chat. SQLite takes the bare username column
// from the row holding max(message_id), i.e. the latest known name.
func (q *Queries) ChatUsers(ctx context.Context, chatID int64) ([]ChatUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, chatUsers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatUsersRow
	for rows.Next() {
		var i ChatUsersRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.LastMessageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMessagesUpTo = `-- name: DeleteMessagesUpTo :exec
DELETE FROM messages
WHERE chat_id = ? AND message_id <= ?
`

type DeleteMessagesUpToParams struct {
	ChatID    int64
	MessageID int64
}

func (q *Queries) DeleteMessagesUpTo(ctx context.Context, arg DeleteMessagesUpToParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesUpTo, arg.ChatID, arg.MessageID)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT OR IGNORE INTO messages (chat_id, message_id, user_id, username, text, sent_at, is_bot, reply_to_username, reply_to_text)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ChatID          int64
	MessageID       int64
	UserID          int64
	Username        string
	Text            string
	SentAt          int64
	IsBot           bool
	ReplyToUsername sql.NullString
	ReplyToText     sql.NullString
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ChatID,
		arg.MessageID,
		arg.UserID,
		arg.Username,
		arg.Text,
		arg.SentAt,
		arg.IsBot,
		arg.ReplyToUsername,
		arg.ReplyToText,
	)
	return err
}

const messagesSince = `-- name: MessagesSince :many
SELECT chat_id, message_id, user_id, username, text, sent_at, is_bot, reply_to_username, reply_to_text FROM messages
WHERE chat_id = ? AND message_id >= ?
ORDER BY message_id
`

type MessagesSinceParams struct {
	ChatID    int64
	MessageID int64
}

func (q *Queries) MessagesSince(ctx context.Context, arg MessagesSinceParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, messagesSince, arg.ChatID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ChatID,
			&i.MessageID,
			&i.UserID,
			&i.Username,
			&i.Text,
			&i.SentAt,
			&i.IsBot,
			&i.ReplyToUsername,
			&i.ReplyToText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneBoundary = `-- name: PruneBoundary :one
SELECT message_id FROM messages
WHERE chat_id = ?
ORDER BY message_id DESC
LIMIT 1 OFFSET ?
`

type PruneBoundaryParams struct {
	ChatID int64
	Offset int64
}

// Returns the ID of the newest message that falls outside the retention window.
func (q *Queries) PruneBoundary(ctx context.Context, arg PruneBoundaryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, pruneBoundary, arg.ChatID, arg.Offset)
	var message_id int64
	err := row.Scan(&message_id)
	return message_id, err
}

const recentMessages = `-- name: RecentMessages :many
SELECT chat_id, message_id, user_id, username, text, sent_at, is_bot, reply_to_username, reply_to_text FROM messages
WHERE chat_id = ?
ORDER BY message_id DESC
LIMIT ?
`

type RecentMessagesParams struct {
	ChatID int64
	Limit  int64
}

// The newest messages of the chat, newest first.
func (q *Queries) RecentMessages(ctx context.Context, arg RecentMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, recentMessages, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ChatID,
			&i.MessageID,
			&i.UserID,
			&i.Username,
			&i.Text,
			&i.SentAt,
			&i.IsBot,
			&i.ReplyToUsername,
			&i.ReplyToText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
