// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Chat struct {
	ID             int64
	Title          string
	Enabled        bool
	SummaryModelID sql.NullInt64
	ChatModelID    sql.NullInt64
	Personality    string
	SettingsJson   string
	UpdatedBy      sql.NullInt64
	UpdatedAt      int64
}

type Message struct {
	ChatID          int64
	MessageID       int64
	UserID          int64
	Username        string
	Text            string
	SentAt          int64
	IsBot           bool
	ReplyToUsername sql.NullString
	ReplyToText     sql.NullString
}

type Model struct {
	ID          int64
	ProviderID  int64
	ModelName   string
	DisplayName string
	ParamsJson  string
}

type Provider struct {
	ID          int64
	OwnerUserID int64
	Kind        string
	Name        string
	BaseUrl     string
	ApiKeyEnc   []byte
	ApiKeyHint  string
	Shared      bool
	CreatedAt   int64
	UpdatedAt   int64
}

type User struct {
	ID        int64
	Username  string
	FirstName string
	CreatedAt int64
}
