// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlcgen

import (
	"context"
)

const chatSummaryModel = `-- name: ChatSummaryModel :one
SELECT models.id, models.provider_id, models.model_name, models.display_name, models.params_json, providers.id, providers.owner_user_id, providers.kind, providers.name, providers.base_url, providers.api_key_enc, providers.api_key_hint, providers.shared, providers.created_at, providers.updated_at
FROM chats
JOIN models ON models.id = chats.summary_model_id
JOIN providers ON providers.id = models.provider_id
WHERE chats.id = ?
`

type ChatSummaryModelRow struct {
	Model    Model
	Provider Provider
}

func (q *Queries) ChatSummaryModel(ctx context.Context, id int64) (ChatSummaryModelRow, error) {
	row := q.db.QueryRowContext(ctx, chatSummaryModel, id)
	var i ChatSummaryModelRow
	err := row.Scan(
		&i.Model.ID,
		&i.Model.ProviderID,
		&i.Model.ModelName,
		&i.Model.DisplayName,
		&i.Model.ParamsJson,
		&i.Provider.ID,
		&i.Provider.OwnerUserID,
		&i.Provider.Kind,
		&i.Provider.Name,
		&i.Provider.BaseUrl,
		&i.Provider.ApiKeyEnc,
		&i.Provider.ApiKeyHint,
		&i.Provider.Shared,
		&i.Provider.CreatedAt,
		&i.Provider.UpdatedAt,
	)
	return i, err
}
