// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlcgen

import (
	"context"
)

const chatSummaryModel = `-- name: ChatSummaryModel :one
SELECT models.id, models.provider_id, models.model_name, models.display_name, models.params_json, providers.id, providers.owner_user_id, providers.kind, providers.name, providers.base_url, providers.api_key_enc, providers.api_key_hint, providers.created_at, providers.updated_at, providers.shared
FROM chats
JOIN models ON models.id = chats.summary_model_id
JOIN providers ON providers.id = models.provider_id
WHERE chats.id = ?
`

type ChatSummaryModelRow struct {
	Model    Model
	Provider Provider
}

func (q *Queries) ChatSummaryModel(ctx context.Context, id int64) (ChatSummaryModelRow, error) {
	row := q.db.QueryRowContext(ctx, chatSummaryModel, id)
	var i ChatSummaryModelRow
	err := row.Scan(
		&i.Model.ID,
		&i.Model.ProviderID,
		&i.Model.ModelName,
		&i.Model.DisplayName,
		&i.Model.ParamsJson,
		&i.Provider.ID,
		&i.Provider.OwnerUserID,
		&i.Provider.Kind,
		&i.Provider.Name,
		&i.Provider.BaseUrl,
		&i.Provider.ApiKeyEnc,
		&i.Provider.ApiKeyHint,
		&i.Provider.CreatedAt,
		&i.Provider.UpdatedAt,
		&i.Provider.Shared,
	)
	return i, err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM models WHERE id = ?
`

func (q *Queries) DeleteModel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteModel, id)
	return err
}

const getModel = `-- name: GetModel :one
SELECT id, provider_id, model_name, display_name, params_json FROM models WHERE id = ?
`

func (q *Queries) GetModel(ctx context.Context, id int64) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelName,
		&i.DisplayName,
		&i.ParamsJson,
	)
	return i, err
}

const insertModel = `-- name: InsertModel :one
INSERT INTO models (provider_id, model_name, display_name, params_json)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertModelParams struct {
	ProviderID  int64
	ModelName   string
	DisplayName string
	ParamsJson  string
}

func (q *Queries) InsertModel(ctx context.Context, arg InsertModelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertModel,
		arg.ProviderID,
		arg.ModelName,
		arg.DisplayName,
		arg.ParamsJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const modelOptionByID = `-- name: ModelOptionByID :one
SELECT models.id, models.provider_id, models.model_name, models.display_name, models.params_json, providers.name AS provider_name, providers.kind AS provider_kind,
       providers.owner_user_id, providers.shared, coalesce(users.username, '') AS owner_username,
       coalesce(users.first_name, '') AS owner_first_name
FROM models
JOIN providers ON providers.id = models.provider_id
LEFT JOIN users ON users.id = providers.owner_user_id
WHERE models.id = ?
`

type ModelOptionByIDRow struct {
	Model          Model
	ProviderName   string
	ProviderKind   string
	OwnerUserID    int64
	Shared         bool
	OwnerUsername  string
	OwnerFirstName string
}

func (q *Queries) ModelOptionByID(ctx context.Context, id int64) (ModelOptionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, modelOptionByID, id)
	var i ModelOptionByIDRow
	err := row.Scan(
		&i.Model.ID,
		&i.Model.ProviderID,
		&i.Model.ModelName,
		&i.Model.DisplayName,
		&i.Model.ParamsJson,
		&i.ProviderName,
		&i.ProviderKind,
		&i.OwnerUserID,
		&i.Shared,
		&i.OwnerUsername,
		&i.OwnerFirstName,
	)
	return i, err
}

const modelWithProvider = `-- name: ModelWithProvider :one
SELECT models.id, models.provider_id, models.model_name, models.display_name, models.params_json, providers.id, providers.owner_user_id, providers.kind, providers.name, providers.base_url, providers.api_key_enc, providers.api_key_hint, providers.created_at, providers.updated_at, providers.shared
FROM models
JOIN providers ON providers.id = models.provider_id
WHERE models.id = ?
`

type ModelWithProviderRow struct {
	Model    Model
	Provider Provider
}

func (q *Queries) ModelWithProvider(ctx context.Context, id int64) (ModelWithProviderRow, error) {
	row := q.db.QueryRowContext(ctx, modelWithProvider, id)
	var i ModelWithProviderRow
	err := row.Scan(
		&i.Model.ID,
		&i.Model.ProviderID,
		&i.Model.ModelName,
		&i.Model.DisplayName,
		&i.Model.ParamsJson,
		&i.Provider.ID,
		&i.Provider.OwnerUserID,
		&i.Provider.Kind,
		&i.Provider.Name,
		&i.Provider.BaseUrl,
		&i.Provider.ApiKeyEnc,
		&i.Provider.ApiKeyHint,
		&i.Provider.CreatedAt,
		&i.Provider.UpdatedAt,
		&i.Provider.Shared,
	)
	return i, err
}

const modelsByOwner = `-- name: ModelsByOwner :many
SELECT models.id, models.provider_id, models.model_name, models.display_name, models.params_json FROM models
JOIN providers ON providers.id = models.provider_id
WHERE providers.owner_user_id = ?
ORDER BY models.id
`

func (q *Queries) ModelsByOwner(ctx context.Context, ownerUserID int64) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, modelsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ModelName,
			&i.DisplayName,
			&i.ParamsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModel = `-- name: UpdateModel :exec
UPDATE models SET model_name = ?, display_name = ?, params_json = ? WHERE id = ?
`

type UpdateModelParams struct {
	ModelName   string
	DisplayName string
	ParamsJson  string
	ID          int64
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) error {
	_, err := q.db.ExecContext(ctx, updateModel,
		arg.ModelName,
		arg.DisplayName,
		arg.ParamsJson,
		arg.ID,
	)
	return err
}

const usableModels = `-- name: UsableModels :many
SELECT models.id, models.provider_id, models.model_name, models.display_name, models.params_json, providers.name AS provider_name, providers.kind AS provider_kind,
       providers.owner_user_id, providers.shared, coalesce(users.username, '') AS owner_username,
       coalesce(users.first_name, '') AS owner_first_name
FROM models
JOIN providers ON providers.id = models.provider_id
LEFT JOIN users ON users.id = providers.owner_user_id
WHERE providers.owner_user_id = ?1 OR providers.shared
ORDER BY providers.shared, models.id
`

type UsableModelsRow struct {
	Model          Model
	ProviderName   string
	ProviderKind   string
	OwnerUserID    int64
	Shared         bool
	OwnerUsername  string
	OwnerFirstName string
}

// Models the user may bind to a chat: their own and shared ones.
func (q *Queries) UsableModels(ctx context.Context, userID int64) ([]UsableModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, usableModels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsableModelsRow
	for rows.Next() {
		var i UsableModelsRow
		if err := rows.Scan(
			&i.Model.ID,
			&i.Model.ProviderID,
			&i.Model.ModelName,
			&i.Model.DisplayName,
			&i.Model.ParamsJson,
			&i.ProviderName,
			&i.ProviderKind,
			&i.OwnerUserID,
			&i.Shared,
			&i.OwnerUsername,
			&i.OwnerFirstName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
