// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package sqlcgen

import (
	"context"
)

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = ?
`

func (q *Queries) DeleteProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProvider, id)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, owner_user_id, kind, name, base_url, api_key_enc, api_key_hint, shared, created_at, updated_at FROM providers WHERE id = ?
`

func (q *Queries) GetProvider(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.ApiKeyHint,
		&i.Shared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProvider = `-- name: InsertProvider :one
INSERT INTO providers (owner_user_id, kind, name, base_url, api_key_enc, api_key_hint, shared)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertProviderParams struct {
	OwnerUserID int64
	Kind        string
	Name        string
	BaseUrl     string
	ApiKeyEnc   []byte
	ApiKeyHint  string
	Shared      bool
}

func (q *Queries) InsertProvider(ctx context.Context, arg InsertProviderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertProvider,
		arg.OwnerUserID,
		arg.Kind,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.ApiKeyHint,
		arg.Shared,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const providersByOwner = `-- name: ProvidersByOwner :many
SELECT id, owner_user_id, kind, name, base_url, api_key_enc, api_key_hint, shared, created_at, updated_at FROM providers WHERE owner_user_id = ? ORDER BY id
`

func (q *Queries) ProvidersByOwner(ctx context.Context, ownerUserID int64) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, providersByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.ApiKeyHint,
			&i.Shared,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :exec
UPDATE providers
SET name = ?, base_url = ?, shared = ?, updated_at = unixepoch()
WHERE id = ?
`

type UpdateProviderParams struct {
	Name    string
	BaseUrl string
	Shared  bool
	ID      int64
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateProvider,
		arg.Name,
		arg.BaseUrl,
		arg.Shared,
		arg.ID,
	)
	return err
}

const updateProviderKey = `-- name: UpdateProviderKey :exec
UPDATE providers
SET name = ?, base_url = ?, api_key_enc = ?, api_key_hint = ?, shared = ?, updated_at = unixepoch()
WHERE id = ?
`

type UpdateProviderKeyParams struct {
	Name       string
	BaseUrl    string
	ApiKeyEnc  []byte
	ApiKeyHint string
	Shared     bool
	ID         int64
}

func (q *Queries) UpdateProviderKey(ctx context.Context, arg UpdateProviderKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderKey,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.ApiKeyHint,
		arg.Shared,
		arg.ID,
	)
	return err
}
