// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertUsage = `-- name: InsertUsage :exec
INSERT INTO llm_usage (chat_id, user_id, model_id, kind, tokens_in, tokens_out) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertUsageParams struct {
	ChatID    int64
	UserID    int64
	ModelID   sql.NullInt64
	Kind      string
	TokensIn  int64
	TokensOut int64
}

func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertUsage,
		arg.ChatID,
		arg.UserID,
		arg.ModelID,
		arg.Kind,
		arg.TokensIn,
		arg.TokensOut,
	)
	return err
}

const usageByUser = `-- name: UsageByUser :many
SELECT llm_usage.user_id, coalesce(users.username, '') AS username, coalesce(users.first_name, '') AS first_name,
       count(*) AS requests, CAST(sum(tokens_in + tokens_out) AS INTEGER) AS tokens
FROM llm_usage
LEFT JOIN users ON users.id = llm_usage.user_id
WHERE llm_usage.chat_id = ? AND llm_usage.created_at >= ?
GROUP BY llm_usage.user_id
ORDER BY requests DESC
LIMIT ?
`

type UsageByUserParams struct {
	ChatID    int64
	CreatedAt int64
	Limit     int64
}

type UsageByUserRow struct {
	UserID    int64
	Username  string
	FirstName string
	Requests  int64
	Tokens    int64
}

func (q *Queries) UsageByUser(ctx context.Context, arg UsageByUserParams) ([]UsageByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, usageByUser, arg.ChatID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageByUserRow
	for rows.Next() {
		var i UsageByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.Requests,
			&i.Tokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageTotals = `-- name: UsageTotals :one
SELECT count(*) AS requests,
       CAST(coalesce(sum(tokens_in), 0) AS INTEGER) AS tokens_in,
       CAST(coalesce(sum(tokens_out), 0) AS INTEGER) AS tokens_out
FROM llm_usage
WHERE chat_id = ? AND created_at >= ?
`

type UsageTotalsParams struct {
	ChatID    int64
	CreatedAt int64
}

type UsageTotalsRow struct {
	Requests  int64
	TokensIn  int64
	TokensOut int64
}

func (q *Queries) UsageTotals(ctx context.Context, arg UsageTotalsParams) (UsageTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, usageTotals, arg.ChatID, arg.CreatedAt)
	var i UsageTotalsRow
	err := row.Scan(&i.Requests, &i.TokensIn, &i.TokensOut)
	return i, err
}
