// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
)

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, username, first_name) VALUES (?, ?, ?)
ON CONFLICT (id) DO UPDATE SET username = excluded.username, first_name = excluded.first_name
`

type UpsertUserParams struct {
	ID        int64
	Username  string
	FirstName string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser, arg.ID, arg.Username, arg.FirstName)
	return err
}
